language: node_js
node_js:
    - 13

services:
    - docker

install:
    - echo "nothing needs to be installed"

before_script:
    - echo "no tests"

script:
    - docker --version
    - docker build -t reverseproxy .
    - docker tag reverseproxy dinhdangkhoa0201/udagram-reverseproxy

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push dinhdangkhoa0201/reverseproxy
